version: 1
default_environment: dev
project_id: 4d3a3d0b-6a2a-4798-afe6-42bb36d2f825
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-postgres
    variant: transferwise
    pip_url: pipelinewise-tap-postgres
    config:
      user: postgres
      port: 5432
      host: localhost
      database: challenge_indicium
      dbname: challenge_indicium
      schemas: public
      filter_schemas: public
      default_replication_method: LOG_BASED

  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: categories
        path: E:\Desafio\indicium\data\csv\public-categories\2025-01-26\public-categories.csv
        demiliter: ','
        keys: [category_id]
      - entity: customers
        path: indicium/data/csv/public-customers/2025-01-26/public-customers.csv
        delimiter: ','
        keys: [customer_id]
      - entity: employee_territories
        path: 
          E:\Desafio\indicium\data\csv\public-employee_territories\2025-01-26\public-employee_territories.csv
        delimiter: ','
        keys: [employee_id, territory_id]
      - entity: employees
        path: E:\Desafio\indicium\data\csv\public-employees\2025-01-26\public-employees.csv
        delimiter: ','
        keys: [employee_id]
      - entity: order_details
        path: 
          E:\Desafio\indicium\data\csv\public-order_details\2025-01-26\public-order_details.csv
        delimiter: ','
        keys: [order_id, product_id]
      - entity: orders
        path: E:\Desafio\indicium\data\csv\public-orders\2025-01-26\public-orders.csv
        delimiter: ','
        keys: [order_id, customer_id, employee_id]
      - entity: products
        path: E:\Desafio\indicium\data\csv\public-products\2025-01-26\public-products.csv
        delimiter: ','
        keys: [product_id, supplier_id, category_id]
      - entity: region
        path: E:\Desafio\indicium\data\csv\public-region\2025-01-26\public-region.csv
        delimiter: ','
        keys: [region_id]
      - entity: shippers
        path: E:\Desafio\indicium\data\csv\public-shippers\2025-01-26\public-shippers.csv
        delimiter: ','
        keys: [shipper_id]
      - entity: suppliers
        path: E:\Desafio\indicium\data\csv\public-suppliers\2025-01-26\public-suppliers.csv
        delimiter: ','
        keys: [supplier_id]
      - entity: territories
        path: 
          E:\Desafio\indicium\data\csv\public-territories\2025-01-26\public-territories.csv
        delimiter: ','
        keys: [territory_id, region_id]
      - entity: us_states
        path: E:\Desafio\indicium\data\csv\public-us_states\2025-01-26\public-us_states.csv
        delimiter: ','
        keys: [state_id]
  loaders:
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      destination_path: indicium_output
      datestamp_format: '{datestamp}'

  - name: target-postgres
    variant: transferwise
    pip_url: pipelinewise-target-postgres
    config:
      host: localhost
      port: 5432
      user: postgres
      dbname: IndiciumDesafio
      schema: public


  utilities:
  - name: salvarcsv_util
    namespace: salvarcsv_util
    commands:
      run_script:
        args: salvarcsv.py
        executable: python
  - name: salvar_arquivos_em_pastas_util
    namespace: salvar_arquivos_em_pastas_util
    commands:
      run_script:
        args: salvar_arquivos_em_pastas.py
        executable: python
jobs:
- name: step_one
  tasks:
  - tap-postgres target-csv
  - salvarcsv_util:run_script
- name: step_two
  tasks:
  - tap-csv target-postgres
schedules:
- name: daily-postg-load
  interval: '@daily'
  job: [step_one, step_two]
